// Auto-generated from people_alumni.html

export const alumniFaculty = [
  'Bagula, BA',
  'Cloete, I (Prof)',
  'Ackerman, C',
  'de Villiers PJA (Prof)',
  'de Villiers H (Dr)',
  'Dodds, RMcD',
  'Du Toit, C',
  'Eloff, J',
  'Engelbrecht, JA',
  'Geldenhuys, J (Prof)',
  'Gouws, EH (Dr)',
  'Hayter, J',
  'Hoffmann, M (Dr)',
  'Lezar, E',
  'Ludik, J (Dr)',
  'Omlin, CW (Dr)',
  'Scheffler, K (Prof)',
  'Uys, JB',
  'Van Deventer, MH',
  'Van der Walt, APJ (Prof)',
];

export const doctoralGraduates = [
  { name: 'Erwin, W', title: 'Landscape aware algorithm selection for feature selection', href: '', year: '2025' },
  { name: 'Baker Effendi, S', title: 'An Approach to Modern Static Analysis with Property Graphs', href: '', year: '2025' },
  { name: 'Werner, W', title: 'Landscape aware algorithm selection for feature selection', href: 'https://scholar.sun.ac.za/handle/10019.1/128812', year: '2023' },
  { name: 'Moeketsi, RI', title: 'Fault Localization and Repair for Grammarware', href: 'http://hdl.handle.net/10019.1/127229', year: '2023' },
  { name: 'Omomule, TG', title: 'Mixtures of heterogeneous experts', href: 'http://hdl.handle.net/10019.1/125916', year: '2022' },
  { name: 'Masakuna, JF', title: 'Active strategies for coordination of solitary robots', href: 'https://scholar.sun.ac.za/handle/10019.1/109111', year: '2020' },
  { name: 'Pretorius, A', title: 'On noise regularised neural networks: initialisation, learning and inference', href: 'http://hdl.handle.net/10019.1/107035', year: '2019' },
  { name: 'Dunaiski, MP', title: 'Using test data to evaluate rankings of entities in large scholarly citation networks', href: 'http://hdl.handle.net/10019.1/105866', year: '2019' },
  { name: 'Marais, L', title: 'Generalised acceptance conditions for symmetric difference nondeterministic finite automata', href: 'http://scholar.sun.ac.za/handle/10019.1/103471', year: '2018' },
  { name: 'Greene, GJ', title: 'Concept-Based Exploration of Rich Semi-Structured Data Collections', href: 'http://scholar.sun.ac.za/handle/10019.1/100859', year: '2017' },
  { name: 'Botha, H-M', title: 'Verifying Android Applications Using Java PathFinder', href: 'http://scholar.sun.ac.za/handle/10019.1/102802', year: '2017' },
  { name: 'Murrell, BS', title: 'Improved Models of Biological Sequence Evolution', href: 'http://scholar.sun.ac.za/handle/10019.1/71870', year: '2012' },
  { name: 'Viktor, HL', title: 'Learning by Cooperation: An Approach to Rule Induction and Knowledge Fusion', href: 'http://scholar.sun.ac.za/handle/10019.1/51319', year: '1999' },
  { name: 'Theron, PZ', title: 'Automatic Acquisition of Two-Level Morphological Rules', href: 'http://scholar.sun.ac.za/handle/10019.1/51149', year: '1999' },
  { name: 'Ewert, SG', title: 'Random Context Picture Grammars', href: 'http://scholar.sun.ac.za/handle/10019.1/49385', year: '1999' },
  { name: 'Engelbrecht, AP', title: 'Sensitivity Analysis of Multilayer Neural Networks', href: 'http://scholar.sun.ac.za/handle/10019.1/51420', year: '1999' },
  { name: 'De Villiers, PJA', title: 'Validation of a Microkernel: A Case Study', href: 'http://scholar.sun.ac.za/handle/10019.1/51539', year: '1999' },
  { name: 'Van Zijl, L', title: 'Generalized Nondeterminism and the Succinct Representation of Regular Languages', href: 'http://scholar.sun.ac.za/handle/10019.1/55541', year: '1997' },
  { name: 'Van der Poel, E', title: 'A Generalization of the Hopfield Single-Layer Recurrent Neural Network', href: 'http://scholar.sun.ac.za/handle/10019.1/55361', year: '1997' },
  { name: 'Ludik, J', title: 'Training, Dynamics, and Complexity of Architecture-Specific Recurrent Neural Networks', href: 'http://scholar.sun.ac.za/handle/10019.1/58622', year: '1994' },
  { name: 'Theron, H', title: 'Specialization by Exclusion: An Approach to Concept Learning', href: 'http://scholar.sun.ac.za/handle/10019.1/54616', year: '1994' },
];

export const mastersGraduates = [
  { name: 'Miller, GD', title: 'Constructing a Knowledge Graph from an Institutional Repository', href: 'https://scholar.sun.ac.za/handle/10019.1/131839', year: '2024' },
  { name: 'Brand, K', title: 'Applied machine learning for radio galaxy classification and anomalous source detection', href: 'https://scholar.sun.ac.za/handle/10019.1/131591', year: '2024' },
  { name: 'Strelitz, BS', title: 'Particle swarm optimization for constrained multimodal function optimization', href: 'https://scholar.sun.ac.za/handle/10019.1/130201', year: '2024' },
  { name: 'Nakiranda, P', title: 'Building identification in aerial imagery using deep learning', href: 'https://scholar.sun.ac.za/handle/10019.1/130619', year: '2024' },
  { name: 'Lang, RD', title: 'Landscape analysis-based automated algorithm selection', href: 'https://scholar.sun.ac.za/handle/10019.1/130243', year: '2024' },
  { name: 'Kane, BR', title: 'Ergo: a gesture-based computer interaction device', href: 'https://scholar.sun.ac.za/handle/10019.1/130463', year: '2024' },
  { name: 'Du Toit, J', title: 'Hierarchical text classification with transformer-based language models', href: 'https://scholar.sun.ac.za/handle/10019.1/130642', year: '2024' },
  { name: 'Dewey, MG', title: 'Large language models and software testing', href: 'https://scholar.sun.ac.za/handle/10019.1/130167', year: '2024' },
  { name: 'Van Zyl, J-P', title: 'Rule Induction with Swarm Intelligence', href: 'http://hdl.handle.net/10019.1/126933', year: '2023' },
  { name: 'Van Zyl, C', title: 'Implementation of the Cavalieri Integral', href: 'http://hdl.handle.net/10019.1/127023', year: '2023' },
  { name: 'Mouton, J', title: 'Integrating Bayesian network structure into normalizing flows and variational autoencoders', href: 'http://hdl.handle.net/10019.1/127316', year: '2023' },
  { name: 'Jackson, J', title: 'Solidifying what is known about calibration artefacts and the development of an educational tool to assist in the teaching of interferometric imaging', href: 'http://hdl.handle.net/10019.1/127243', year: '2023' },
  { name: 'Dreyer, A', title: 'Using transformers to assign ICD codes to medical notes', href: 'http://hdl.handle.net/10019.1/127086', year: '2023' },
  { name: 'Van Litsenborgh, PS', title: 'An investigation into performance-related issues of regular expression matching', href: 'http://hdl.handle.net/10019.1/126045', year: '2022' },
  { name: 'Rossouw, CJ', title: 'Coverage directed algorithms for test suite construction from LR-automata', href: 'http://hdl.handle.net/10019.1/124734', year: '2022' },
  { name: 'Habeck, M', title: 'The generation of longest optimal box repetition-free words', href: 'http://hdl.handle.net/10019.1/124592', year: '2022' },
  { name: 'Burger, CN', title: 'An extension of the linear regression model for improved vessel trajectory prediction utilising a priori AIS Information', href: 'http://hdl.handle.net/10019.1/124543', year: '2022' },
  { name: 'Bekcer, AB', title: 'Application of statistical pattern recognition and deep learning for morphological classification in radio astronomy', href: 'http://hdl.handle.net/10019.1/124690', year: '2022' },
  { name: 'Mohamed, Z', title: 'Explaining neural networks used for modeling credit risk', href: 'http://hdl.handle.net/10019.1/110117', year: '2021' },
  { name: 'Steenkamp, C', title: 'Multi-guide particle swarm optimization for many-objective optimization problems', href: 'http://hdl.handle.net/10019.1/110568', year: '2021' },
  { name: 'Erwin, KH', title: 'Set-based particle swarm optimization for portfolio optimization', href: 'http://hdl.handle.net/10019.1/123658', year: '2021' },
  { name: 'Strydom, S', title: 'Automatic assignment of diagnosis codes to free-form text medical notes', href: 'http://hdl.handle.net/10019.1/123654', year: '2021' },
  { name: 'Van Biljon, E', title: 'Initialisation of noise-regularised neural networks', href: 'http://hdl.handle.net/10019.1/123661', year: '2021' },
  { name: 'Steyl, CC', title: 'A deep framework for predictive maintenance', href: 'http://hdl.handle.net/10019.1/123836', year: '2021' },
  { name: 'Du Toit, N', title: 'Concrete and symbolic linearisability checking of non-blocking concurrent data structures', href: 'http://hdl.handle.net/10019.1/123925', year: '2021' },
  { name: 'Christoph, M', title: 'Parallel Monte-Carlo tree search in distributed environments', href: 'http://hdl.handle.net/10019.1/108014', year: '2020' },
  { name: 'Leid, A', title: 'Testing smart contracts', href: 'http://hdl.handle.net/10019.1/108088', year: '2020' },
  { name: 'Berndt, J', title: 'Scaling the ConceptCloud browser to very large semi-structured data sets: architecture and data completion', href: 'http://hdl.handle.net/10019.1/109315', year: '2020' },
  { name: 'Taljaard, MH', title: 'Optimised constraint solving for real-world problems', href: 'http://hdl.handle.net/10019.1/107292', year: '2019' },
  { name: 'Martin, JJ', title: 'Creating 3D models using reconstruction techniques', href: 'http://scholar.sun.ac.za/handle/10019.1/104919', year: '2018' },
  { name: 'Schreiber, S', title: 'Texture synthesis with neural networks', href: 'http://scholar.sun.ac.za/handle/10019.1/104868', year: '2018' },
  { name: 'Thom, JD', title: 'Combining tree kernels and text embeddings for plagiarism detection', href: 'http://scholar.sun.ac.za/handle/10019.1/103550', year: '2018' },
  { name: 'Breytenbach, JA', title: 'Design and evaluation of a formula cache for SMT-based bounded model checking tools', href: 'http://scholar.sun.ac.za/handle/10019.1/103809', year: '2018' },
  { name: 'Wiehman, S', title: 'Investigating fully convolutional networks for bio-image segmentation', href: 'http://scholar.sun.ac.za/handle/10019.1/103581', year: '2018' },
  { name: 'Esterhuizen, MH', title: 'Test case generation for context free grammars', href: 'http://scholar.sun.ac.za/handle/10019.1/103802', year: '2018' },
  { name: 'Weideman, NH', title: 'Static Analysis of Regular Expressions', href: 'http://scholar.sun.ac.za/handle/10019.1/102879', year: '2017' },
  { name: 'Venter, DW', title: 'Detecting and Quantifying Resource Contention in Concurrent Programs', href: 'http://scholar.sun.ac.za/handle/10019.1/98838', year: '2016' },
  { name: 'Mwale, M', title: 'Modelling the Dynamics of the Bitcoin Blockchain', href: 'http://scholar.sun.ac.za/handle/10019.1/98844', year: '2016' },
  { name: 'Brand, DJ', title: 'Automatic Prediction of Comment Quality', href: 'http://scholar.sun.ac.za/handle/10019.1/98818', year: '2016' },
  { name: 'Jordaan, PJG', title: 'Impendulo: A Tool for Analysing Programmer Behaviour', href: 'http://scholar.sun.ac.za/handle/10019.1/97081', year: '2015' },
  { name: 'Fourie, R', title: 'A Parallel Cellular Automaton Simulation Framework Using CUDA', href: 'http://scholar.sun.ac.za/handle/10019.1/96961', year: '2015' },
  { name: 'Coetzee, AL', title: 'Combining Reverse Debugging and Live Programming Towards Visual Thinking in Computer Programming', href: 'http://scholar.sun.ac.za/handle/10019.1/96853', year: '2015' },
  { name: 'Babalola, OT', title: 'Automatic Recognition and Interpretation of Finite State Automata Diagrams', href: 'http://scholar.sun.ac.za/handle/10019.1/97814', year: '2015' },
  { name: 'Van Niekerk, F', title: 'Decision Forests for Computer Go Feature Learning', href: 'http://scholar.sun.ac.za/handle/10019.1/86280', year: '2014' },
  { name: 'Kruger, RP', title: 'Virtual World Accessibility: A Multitool Approach', href: 'http://scholar.sun.ac.za/handle/10019.1/95932', year: '2014' },
  { name: 'Dunaiski, MP', title: 'Analysing Ranking Algorithms and Publication Trends on Scholarly Citation Networks', href: 'http://scholar.sun.ac.za/handle/10019.1/96106', year: '2014' },
  { name: 'Uwimbabazi, A', title: 'Extended Probabilistic Symbolic Execution', href: 'http://scholar.sun.ac.za/handle/10019.1/85804', year: '2013' },
  { name: 'Theron, PJ', title: 'Criteria for the Evaluation of Private Cloud Computing', href: 'http://scholar.sun.ac.za/handle/10019.1/85858', year: '2013' },
  { name: 'Rajaona, SF', title: 'An Algebraic Framework for Reasoning About Security', href: 'http://scholar.sun.ac.za/handle/10019.1/79869', year: '2013' },
  { name: 'Durant, K', title: 'Investigating the Non-termination of Affine Loops', href: 'http://scholar.sun.ac.za/handle/10019.1/80052', year: '2013' },
  { name: 'De Villiers, PF', title: 'Constructing Topic-Based Twitter Lists', href: 'http://scholar.sun.ac.za/handle/10019.1/80054', year: '2013' },
  { name: 'Buys, JM', title: 'Probabilistic Tree Transducers for Grammatical Error Correction', href: 'http://scholar.sun.ac.za/handle/10019.1/85592', year: '2013' },
  { name: 'Bester, WHK', title: 'Bug-Finding and Test Case Generation for Java Programs by Symbolic Execution', href: 'http://scholar.sun.ac.za/handle/10019.1/85832', year: '2013' },
  { name: 'Venter, WJ', title: 'An Embodied Conversational Agent with Autistic Behaviour', href: 'http://scholar.sun.ac.za/handle/10019.1/20115', year: '2012' },
  { name: 'Redelinghuys, GJ-W', title: 'Symbolic String Execution', href: 'http://scholar.sun.ac.za/handle/10019.1/20335', year: '2012' },
  { name: 'Kruger, PJH', title: 'Cellphone Banking at the Bottom of the Pyramid', href: 'http://scholar.sun.ac.za/handle/10019.1/19975', year: '2012' },
  { name: 'Huysamen, NF', title: 'FATKID: A Finite Automaton Toolkit', href: 'http://scholar.sun.ac.za/handle/10019.1/71684', year: '2012' },
  { name: 'Goldberg, AS', title: 'Investigating Credit Based Mechanisms for Enhancing Performance in Wireless Ad Hoc Networks', href: 'http://scholar.sun.ac.za/handle/10019.1/71757', year: '2012' },
  { name: 'Botha, SG', title: 'The Effect of Evolutionary Rate Estimation Methods on Correlations Observed Between Substitution Rates in Models of Evolution', href: 'http://scholar.sun.ac.za/handle/10019.1/19938', year: '2012' },
  { name: 'Bezuidenhout, JA', title: 'Automated Program Generation: Bridging the Gap Between Model and Implementation', href: 'http://scholar.sun.ac.za/handle/10019.1/19584', year: '2012' },
  { name: 'Msiska, MF', title: 'A Visual Programming Environment for Authoring ASD Therapy Tools', href: 'http://scholar.sun.ac.za/handle/10019.1/17939', year: '2011' },
  { name: 'Minoarivelo, HO', title: 'Probabilistic Modelling of the Evolution of Ecological Interaction Networks', href: 'http://scholar.sun.ac.za/handle/10019.1/17990', year: '2011' },
  { name: 'Kassa, DF', title: 'Analytic Models of TCP Performance', href: 'http://scholar.sun.ac.za/handle/10019.1/16608', year: '2011' },
  { name: 'Hayward, PJ', title: 'Parallel Likelihood Calculations for Phylogenetic Trees', href: 'http://scholar.sun.ac.za/handle/10019.1/17919', year: '2011' },
  { name: 'Botha, LW', title: 'Modeling Online Social Networks Using Quasi-Clique Communities', href: 'http://scholar.sun.ac.za/handle/10019.1/17859', year: '2011' },
  { name: 'Bergh, JR', title: 'Ontology Comprehension', href: 'http://scholar.sun.ac.za/handle/10019.1/6517', year: '2011' },
  { name: 'Adams, RC', title: 'Implementation of Cell Clustering in Cellular Automata', href: 'http://scholar.sun.ac.za/handle/10019.1/6674', year: '2011' },
  { name: 'Schulze, W', title: 'A Formal Language Theory Approach to Music Generation', href: 'http://scholar.sun.ac.za/handle/10019.1/4157', year: '2010' },
  { name: 'Odendaal, MJ', title: 'Business Process Modelling Using Model Checking and the Theory of Constraints', href: 'http://scholar.sun.ac.za/handle/10019.1/4269', year: '2010' },
  { name: 'Fath Elrahman, TM', title: 'QoS Routing in IP Networks Using Multi-Constrained Computational Methods', href: 'http://scholar.sun.ac.za/handle/10019.1/4098', year: '2010' },
  { name: 'Fasan, MO', title: 'Distributed Binary Decision Diagrams', href: 'http://scholar.sun.ac.za/handle/10019.1/5411', year: '2010' },
  { name: 'Boulkaibet, I', title: 'Modelling Collaborative Motion in Mobile Ad Hoc Networks', href: 'http://scholar.sun.ac.za/handle/10019.1/5155', year: '2010' },
  { name: 'Stapelberg, D', title: 'Link Failure Recovery Among Dynamic Routes in Telecommunication Networks', href: 'http://scholar.sun.ac.za/handle/10019.1/2591', year: '2009' },
  { name: 'Kriek, AM', title: 'RoboCup Formation Modeling', href: 'http://scholar.sun.ac.za/handle/10019.1/2810', year: '2009' },
  { name: 'Greeff, GJ', title: 'Interactive Voxel Terrain Design Using Procedural Techniques', href: 'http://scholar.sun.ac.za/handle/10019.1/2631', year: '2009' },
  { name: 'Fourie, JF', title: 'Reducing Communication in Distributed Model Checking', href: 'http://scholar.sun.ac.za/handle/10019.1/2176', year: '2009' },
  { name: 'Crous, CB', title: 'Autonomous Robot Path Planning', href: 'http://scholar.sun.ac.za/handle/10019.1/2519', year: '2009' },
  { name: 'Chamberlain, ME', title: 'A 3D Virtual Environment Development Platform for ASD Therapy Tools', href: 'http://scholar.sun.ac.za/handle/10019.1/2634', year: '2009' },
  { name: 'Taha, MAMS', title: 'Regulated Rewriting in Formal Language Theory', href: 'http://scholar.sun.ac.za/handle/10019.1/1600', year: '2008' },
  { name: 'Smal, E', title: 'Automated Brick Sculpture Construction', href: 'http://scholar.sun.ac.za/handle/10019.1/2288', year: '2008' },
  { name: 'Lusilao-Zodi, G-A', title: 'A Bandwidth Market in an IP Network', href: 'http://scholar.sun.ac.za/handle/10019.1/1933', year: '2008' },
  { name: 'Du Preez, H', title: 'GrailKnights: An Automaton Mass Manipulation Package for Enhanced Pattern Analysis', href: 'http://scholar.sun.ac.za/handle/10019.1/2902', year: '2008' },
  { name: 'Welgemoed, Johan', title: 'A Prototype System for Machine Translation from English to South African Sign Language Using Synchronous Tree Adjoining Grammars', href: 'http://scholar.sun.ac.za/handle/10019.1/19892', year: '2007' },
  { name: 'Seotsanyana, M', title: 'Formal Specification and Verification of Safety Interlock Systems: A Comparative Case Study', href: 'http://scholar.sun.ac.za/handle/10019.1/2162', year: '2007' },
  { name: 'Mazandu, GK', title: 'Traffic Engineering Using Multipath Routing Approaches', href: 'http://scholar.sun.ac.za/handle/10019.1/2732', year: '2007' },
  { name: 'Gerber, DB', title: 'A Model Checker for the LF System', href: 'http://scholar.sun.ac.za/handle/10019.1/19597', year: '2007' },
  { name: 'Baruani, AJ', title: 'Network Engineering Using Multi-Objective Evolutionary Algorithms', href: 'http://scholar.sun.ac.za/handle/10019.1/21548', year: '2007' },
  { name: 'Raitt, LA', title: 'Random Generation of Finite Automata Over the Domain of the Regular Languages', href: 'http://scholar.sun.ac.za/handle/10019.1/19646', year: '2006' },
  { name: 'Müller, G', title: 'Minimization of Symmetric Difference Finite Automata', href: 'http://scholar.sun.ac.za/handle/10019.1/1922', year: '2006' },
  { name: 'Louw, F', title: 'A Program Slicer for LF', href: 'http://scholar.sun.ac.za/handle/10019.1/17378', year: '2006' },
  { name: 'Grobler, LD', title: 'A Kernel to Support Computer-Aided Verification of Embedded Software', href: 'http://scholar.sun.ac.za/handle/10019.1/2479', year: '2006' },
  { name: 'Grift, W', title: 'Visualizing QoS in Networks', href: 'http://scholar.sun.ac.za/handle/10019.1/17356', year: '2006' },
  { name: 'Combrink, AJ', title: 'A Preprocessor for an English-to-Sign Language Machine Translation System', href: 'http://scholar.sun.ac.za/handle/10019.1/2832', year: '2005' },
  { name: 'Barker, DD', title: 'Computer Facial Animation for Sign Language Visualization', href: 'http://scholar.sun.ac.za/handle/10019.1/50300', year: '2005' },
  { name: 'Swart, R', title: 'A Language to Support Verification of Embedded Software', href: 'http://scholar.sun.ac.za/handle/10019.1/49823', year: '2004' },
  { name: 'De Jongh, AB', title: 'Neural Network Ensembles', href: 'http://scholar.sun.ac.za/handle/10019.1/50035', year: '2004' },
  { name: 'Connan, J', title: 'Collection, Evaluation and Selection of Scientific Literature: Machine Learning, Bibliometrics and the World Wide Web', href: 'http://scholar.sun.ac.za/handle/10019.1/49886', year: '2004' },
  { name: 'Combrink, JJ', title: 'A Bandwidth Market for Traffic Engineering in Telecommunication Networks', href: 'http://scholar.sun.ac.za/handle/10019.1/49808', year: '2004' },
  { name: 'Botha, M', title: 'Online Traffic Engineering for MPLS Networks', href: 'http://scholar.sun.ac.za/handle/10019.1/50049', year: '2004' },
  { name: 'Snyders, S', title: 'Inductive Machine Learning Bias in Knowledge-Based Neurocomputing', href: 'http://scholar.sun.ac.za/handle/10019.1/53463', year: '2003' },
  { name: 'Myburgh, WD', title: 'Development of a Tool to Test Computer Protocols', href: 'http://scholar.sun.ac.za/handle/10019.1/53363', year: '2003' },
  { name: 'Müller, KE', title: 'MPLS-Based Recovery', href: 'http://scholar.sun.ac.za/handle/10019.1/53506', year: '2003' },
  { name: 'Kruger, AF', title: 'Machine Learning, Data Mining, and the World Wide Web: Design of Special-Purpose Search Engines', href: 'http://scholar.sun.ac.za/handle/10019.1/53492', year: '2003' },
  { name: 'Kroon, RS', title: 'Support Vector Machines, Generalization Bounds, and Transduction', href: 'http://scholar.sun.ac.za/handle/10019.1/16375', year: '2003' },
  { name: 'Hakl, HM', title: 'Computer-Controlled Human Body Coordination', href: 'http://scholar.sun.ac.za/handle/10019.1/49756', year: '2003' },
  { name: 'Bull, JJD', title: 'A Comparison of Two Different Model Checking Techniques', href: 'http://scholar.sun.ac.za/handle/10019.1/53235', year: '2003' },
  { name: 'Andrag, WH', title: 'Reinforcement Learning for Routing in Communication Networks', href: 'http://scholar.sun.ac.za/handle/10019.1/53570', year: '2003' },
  { name: 'De Kock, JM', title: 'Optimal Management of MPLS Networks', href: 'http://scholar.sun.ac.za/handle/10019.1/52977', year: '2002' },
  { name: 'Wessels, T', title: 'Hidden Markov Models for On-Line Signature Verification', href: 'http://scholar.sun.ac.za/handle/10019.1/52876', year: '2001' },
  { name: 'Walsh, DA', title: 'Automatic Detection of Image Orientation Using Support Vector Machines', href: 'http://scholar.sun.ac.za/handle/10019.1/52717', year: '2001' },
  { name: 'Wahabi, AR', title: 'Resource Management in IP Networks', href: 'http://scholar.sun.ac.za/handle/10019.1/52436', year: '2001' },
  { name: 'Van Zyl, J', title: 'Modelling Chaotic Systems with Neural Networks: Application to Seismic Event Predicting in Gold Mines', href: 'http://scholar.sun.ac.za/handle/10019.1/4580', year: '2001' },
  { name: 'Van Riet, FA', title: 'LF: A Language for Reliable Embedded Systems', href: 'http://scholar.sun.ac.za/handle/10019.1/52322', year: '2001' },
  { name: 'Esterhuyse, E', title: 'On Providing an Efficient and Reliable Virtual Block Storage Service', href: 'http://scholar.sun.ac.za/handle/10019.1/51862', year: '2001' },
  { name: 'Eloff, JJ', title: 'A Software Restructuring Tool for Oberon', href: 'http://scholar.sun.ac.za/handle/10019.1/52134', year: '2001' },
  { name: 'Du Toit, C', title: 'The Use of Temporal Context in the Generation of Strings', href: 'http://scholar.sun.ac.za/handle/10019.1/53183', year: '2001' },
  { name: 'Bagula, BA', title: 'Traffic Engineering Label Switched Paths', href: 'http://scholar.sun.ac.za/handle/10019.1/53196', year: '2001' },
  { name: 'Loubser, JJ', title: 'Device Drivers: A Comparison of Different Development Strategies', href: 'http://scholar.sun.ac.za/handle/10019.1/51690', year: '2000' },
  { name: 'Inggs, CP', title: 'An LTL Verification System Based on Automata Theory', href: 'http://scholar.sun.ac.za/handle/10019.1/51128', year: '1999' },
  { name: 'Inggs, AM', title: 'Efficient Call Management in Broadband Networks', href: 'http://scholar.sun.ac.za/handle/10019.1/51254', year: '1999' },
  { name: 'Geldenhuys, J', title: 'Efficiency Issues in the Design of a Model Checker', href: 'http://scholar.sun.ac.za/handle/10019.1/51253', year: '1999' },
  { name: 'De Villiers, JA', title: 'Micro-Kernel Support for a Lightweight Extensible Workstation Operating System', href: 'http://scholar.sun.ac.za/handle/10019.1/51341', year: '1999' },
  { name: 'De Wet, MJdV', title: 'A Development Environment for Reactive Systems', href: 'http://scholar.sun.ac.za/handle/10019.1/55797', year: '1998' },
  { name: 'Staven, S', title: 'Entropy Maximized Queueing Networks', href: 'http://scholar.sun.ac.za/handle/10019.1/55117', year: '1996' },
  { name: 'Keyser, PW', title: 'Transaction Management in Multidatabase Systems', href: 'http://scholar.sun.ac.za/handle/10019.1/55322', year: '1996' },
  { name: 'Winckler, CJ', title: 'A Comprehensive Framework for SQL Query Execution in Distributed Multidatabase Systems', href: 'http://scholar.sun.ac.za/handle/10019.1/58637', year: '1995' },
  { name: 'Phillips, GP', title: 'Transient Models For Queueing Networks', href: 'http://scholar.sun.ac.za/handle/10019.1/54928', year: '1995' },
  { name: 'Lockley, GJ', title: 'The Design of a Specification Language Suitable for the Generation of Compilers', href: 'http://scholar.sun.ac.za/handle/10019.1/58723', year: '1995' },
  { name: 'Kriel, CF', title: 'Order Independent Multiclass Queues: A New Class of Quasi-Reversible Queues', href: 'http://scholar.sun.ac.za/handle/10019.1/54822', year: '1995' },
  { name: 'Zimmerman, AD', title: 'Parallelizing a Bi-Directional Chart Parser for a Multicomputer', href: 'http://scholar.sun.ac.za/handle/10019.1/58511', year: '1994' },
  { name: 'Muller, PJ', title: 'An Environment for Distributed Programming on a Multicomputer', href: 'http://scholar.sun.ac.za/handle/10019.1/58250', year: '1994' },
  { name: 'Visser, WC', title: 'A Run-Time Environment for a Validation Language', href: 'http://scholar.sun.ac.za/handle/10019.1/57861', year: '1993' },
  { name: 'Van der Poel, E', title: 'Visualizing Neural Networks', href: 'http://scholar.sun.ac.za/handle/10019.1/58223', year: '1993' },
  { name: 'Howard, WT', title: 'An Efficient Resilient Page Store', href: 'http://scholar.sun.ac.za/handle/10019.1/57848', year: '1993' },
  { name: 'Engelbrecht, AP', title: 'Modelling Algorithms for the South African Telephone Network', href: 'http://scholar.sun.ac.za/handle/10019.1/58040', year: '1993' },
  { name: 'Ackerman, MC', title: 'Kernel Support for Embedded Reactive Systems', href: 'http://scholar.sun.ac.za/handle/10019.1/58022', year: '1993' },
  { name: 'Ackerman, CC', title: 'Providing Mechanical Support for Program Development in a Weakest Precondition Calculus', href: 'http://scholar.sun.ac.za/handle/10019.1/79317', year: '1993' },
  { name: 'Viktor, HL', title: 'A Comparative Study of Distributed Database Recovery Techniques', href: 'http://scholar.sun.ac.za/handle/10019.1/69486', year: '1992' },
  { name: 'Meumann, MD', title: 'The Design and Implementation of a Communication Kernel for a Distributed Database System', href: 'http://scholar.sun.ac.za/handle/10019.1/69424', year: '1991' },
  { name: 'Ludik, J', title: '\'n Meerdoelige Simulasie Omgewing vir die Ontwikkeling van Neurale Netwerke', href: 'http://scholar.sun.ac.za/handle/10019.1/69322', year: '1991' },
  { name: 'Fouche, W', title: 'An Efficient Kernel to Support the Client-Server Model', href: 'http://scholar.sun.ac.za/handle/10019.1/69089', year: '1991' },
  { name: 'Deacon, AE', title: 'Concurrency Control Mechanisms for Multidatabase Systems', href: 'http://scholar.sun.ac.za/handle/10019.1/69128', year: '1991' },
  { name: 'Barnard, DC', title: 'Reducing the State Explosion Problem During Model Checking', href: 'http://scholar.sun.ac.za/handle/10019.1/69386', year: '1991' },
  { name: 'Theron, H', title: 'A Survey and Comparison of Well-Known Concept Induction Algorithms', href: 'http://scholar.sun.ac.za/handle/10019.1/67192', year: '1990' },
  { name: 'Lamprecht, SM', title: 'A Comparative Study of Distributed Query Optimization Methods', href: 'http://scholar.sun.ac.za/handle/10019.1/68640', year: '1990' },
  { name: 'Harmse, MFP', title: 'The Analytic Modelling of DASD Subsystems', href: 'http://scholar.sun.ac.za/handle/10019.1/68998', year: '1990' },
  { name: 'Greeff, J', title: 'Derivation and Implementation of an Extended Entity-Relationship Data Model', href: 'http://scholar.sun.ac.za/handle/10019.1/68699', year: '1990' },
  { name: 'Crosby, SA', title: 'Queueing Networks with Blocking and Simultaneous Resource Possession', href: 'http://scholar.sun.ac.za/handle/10019.1/67356', year: '1990' },
];